### PR TITLE
Fix credit note color

### PR DESCRIPTION
**Pull request by mbayopanda**
This PR fix the color of the credit note button to `text-danger`

### CODE REVIEW

**Comment by sfount** [comment]
It looks like some additional commits are included in this pull request. Potentially it should be rebased with `vanga`/`master` to only introduce the most recent commit.

**Comment by jniles** [comment]
@mbayopanda, the only way you'll get rid of these commits is to use `cherry-pick`.  @dedrickenc can teach you - he did it a week ago.

**Comment by jniles** [comment]
@mbayopanda, there a few conflicts to resolve now.  Let me know when these get resolved - it will be really useful to have these changes!

**Comment by mbayopanda** [comment]
@jniles this can be closed because #205 fix also the color for the credit note link

**Comment by jniles** [comment]
@mbayopanda, thanks.

**Pull request closed without merging**
